# Generated by Django 3.1.5 on 2021-05-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
