# Generated by Django 3.1.5 on 2021-02-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0005_usermessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
