# Generated by Django 3.1.5 on 2021-02-08 14:48

from django.db import migrations, models
import main_gusto.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0006_auto_20210207_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=1, upload_to=main_gusto.models.Category.get_file_name_category),
            preserve_default=False,
        ),
    ]
