# Generated by Django 3.1.5 on 2021-02-08 19:31

from django.db import migrations, models
import main_gusto.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_gusto', '0007_category_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to=main_gusto.models.Info.get_file_name_info)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
